spring:
  security:
    oauth2:
      client:
        registration:
          tdf:
            client-id: cloudoauth2samplejwt
            client-secret: cloudoauth2samplejwt
            provider: tdf
            client-name: 太极统一认证
            authorization-grant-type: authorization_code
            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          tdf:
            user-name-attribute: "name"
            authorization-uri: ${authorization-server-url}/oauth/authorize
            token-uri: ${authorization-server-url}/oauth/token
            user-info-uri: ${authorization-server-url}/user/me
            jwk-set-uri: ${authorization-server-url}/.well-known/jwks.json

# 自定义变量；认证服务器地址
authorization-server-url: http://192.168.99.77:9998
#authorization-server-url: http://localhost:9999
