
server:
  port: 8082

spring:
  application:
    name: resource
  cloud:
    client:
      hostname: localhost
  profiles:
    active: github
#    active: tdf
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://dev-269876.okta.com/oauth2/default/v1/keys
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.boot.autoconfigure: INFO